### PR TITLE
AUTO_CLOSE Functionality

### PR DESCRIPTION
**Pull request by Sweets**
```
Added AUTO_CLOSE, which will close pull requests upon commenting. AUTO_CLOSE expected to be a boolean in `settings.py`, but can realistically be anything that evaluates to True or False.

A check has also been added to see if the pull request is already closed, and if so, PRBot will skip commenting/closing the pull request.

Lastly, I modified line 29, which had a FIXME comment.
```

Hopefully everything is now up to par with your specifications. :)

### CODE REVIEW

**Comment by ajdlinux** [comment]
Thanks, looks a lot better! I'll give this a quick test when I get the chance sometime in the next couple of days but otherwise looks good to merge.

**Comment by Electromaster232** [comment]
beat me to it! Look good though!

**Comment by Sweets** [comment]
Anything new, i.e. has this been tested yet? @ajdlinux

**Comment by ajdlinux** [comment]
Sorry I've been super busy these last couple of weeks! I'll take a look now.

**Comment by Sweets** [comment]
Just a friendly reminder that this PR is still open. :)

**Comment by JL2210** [comment]
@ajdlinux

**Comment by ajdlinux** [comment]
I am, uh, the world's greatest maintainer. Sorry.

I should note that per https://github.com/ajdlinux/PRBot/issues/4#issuecomment-555308358, I think actions requiring contributor/maintainer access to a repository are stretching the scope of PRBot and should really be done using the GitHub Apps API and the many bots already out there which make use of it. I want to keep PRBot nice and simple and focused on the specific problem it set out to solve which was autoresponding to mirror repositories where we don't have contributor access.

But I'll merge this anyway. Thanks and sorry for the wait!

**Comment by ajdlinux** [comment]
I've pushed a slightly changed version of this to address a couple of minor issues. Thanks for the patches!

**Pull request closed without merging**
